spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: alex
    password: Magic_nava02
    driverClassName: oracle.jdbc.driver.OracleDriver
jpa:
  show-sql: true
  open-in-view: false
  hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Oracle10gDialect
